source 'https://github.com/cocoapods/specs'
source 'https://github.com/jivochat/cocoapods-repo'

# Uncomment this line to define a global platform for your project
# Uncomment this line to define a global platform for your project
platform :ios, '14.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  pod 'GoogleUtilities'
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_swift_libraries = [
      '__swift_FORCE_LOAD_$_swift_Builtin_float',
      '__swift_FORCE_LOAD_$_swift_errno',
      '__swift_FORCE_LOAD_$_swift_math',
      '__swift_FORCE_LOAD_$_swift_signal',
      '__swift_FORCE_LOAD_$_swift_stdio',
      '__swift_FORCE_LOAD_$_swift_time',
      '__swift_FORCE_LOAD_$_swiftsys_time',
      '__swift_FORCE_LOAD_$_swiftunistd'
    ]
    target.build_configurations.each do |config|
      flutter_additional_swift_libraries.each do |library|
        config.build_settings['OTHER_LDFLAGS'] ||= ['$(inherited)']
        config.build_settings['OTHER_LDFLAGS'] << "-force_load #{library}"
      end
    end
  end
end


target 'ImageNotification' do
  use_frameworks!
  pod 'GoogleUtilities'
  pod 'Firebase/Messaging'
end