source 'https://github.com/cocoapods/specs'
source 'https://github.com/jivochat/cocoapods-repo'

# Uncomment this line to define a global platform for your project
platform :ios, '14.0.0'



# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  pod 'GoogleUtilities'
  use_frameworks! :linkage => :static
  use_modular_headers!

  pod 'FBAudienceNetwork', '6.15.2'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '11.2.0'
end

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     file.remove_from_build_phases if file.name.include?("Assets.car")
#     file.remove_from_build_phases if file.name.include?("PrivacyInfo.xcprivacy")
#     flutter_additional_ios_build_settings(target)
#     target.build_configurations.each do |config|
#       config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
#
#     end
#   end
# end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.is_a?(Xcodeproj::Project::Object::PBXNativeTarget)
      target.resources_build_phase.files.each do |file|
        if file.file_ref && (file.file_ref.path.include?("Assets.car") || file.file_ref.path.include?("PrivacyInfo.xcprivacy"))
          puts "Removing duplicate file: #{file.file_ref.path}" # Log para depuração
          file.remove_from_project
        end
      end
    end

    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end






target 'ImageNotification' do
  use_frameworks! :linkage => :static
  pod 'Firebase/Messaging'
  pod 'GoogleUtilities'
end
